name: 安装musl-libc
run-name: 安装musl-libc
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 安装musl-libc
        run: |
          git clone https://git.musl-libc.org/git/musl
          cd musl
          ls
          ./configure
          make
          sudo make install