name: 安装musl-libc
run-name: 安装musl-libc
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: git clone https://git.musl-libc.org/git/musl
      - run: |
          pwd
          cd musl
          pwd
          ls
          ./configure
          make
          make install